10/31　~16:00
作業したことをメモる。

①DC:A6:32:8C:8F:AA　と　②E4:5F:01:25:11:B6
やりたいこと：Send and Reserveのテスト　まずは両ラズパイをBLE通信できる状態にするところから始める

https://qiita.com/shippokun/items/0953160607833077163f　参考

試してみるが上手くいかない　　→　　最初からなぞろうの会　
①②に関連パッケージインストール＋bluezインストール なおできない。　お互いが認識できてない。
https://pc.atsuhiro-me.net/entry/2021/06/03/155123　
boot/config.txt　をいじればどうにかなる？　次回そこから。

11/8 
boot/config.txt に　# dtoverlay=disble-bt を追加。
再度BLE通信挑戦。　成功！！

main.py 行けるか試してみる？
書いてあること試す
$ sudo apt-get install git
$ git clone https://github.com/T3pp31/BLE_Blockchain
$ cd BLE_Blockchain
$ python3 install_package.py
setting.jsonをお互いのラズパイで書き換え。

送信されてくるデータを待っているが動いているのか不明。　実行は出来てるっぽい。　l2cap_server.pyの送信されてくるデータを待っています。までは見れる。
#32について　言われなくてもそれはわかってる。どうすればいのかはわからん。

11/9
main.py いじりながらやっていくしか。 ②にVScodeいれた。
11/10 
一旦形式は出来た。動かしながらやってみる。
11/11
main.py の送信ブロックチェーンを削った部分を試してみる。
実行結果：changing discoverable on succeeded 改行して　学籍番号 near_device 備考　0、1は出たけどその後Traceback。
49行目のdelete_excess_data(df)に対してTypeError: 'module' object is not callable　一旦ここまで。
main.pyで試すのはきつい気がする。　独自で動くかチェック。宮前君と連携とりたい。

11/15
試してみた？とりあえずgithubに作ったの載せた。①をssh接続できるようにした。https://qiita.com/c60evaporator/items/2384416f1122ae124f50　参照
ポートかなんかで引っ掛かる。明日やってみて考える？
11/16
・IP固定したい。　　　　　　　　　　　　→　12/5までにやる
・送受信分けて試してみたい。　　　　　　→　次回試す
・socket云々を調査、実行したい。　　　　→　福富君に聞きつつ
・serevr.pyのportを4097にしてみる？　　　→　次回試す


11/17
send.pyとrece.pyに分けてみた。試してみましょう。

kaz@raspberrypi:~/Test $  cd /home/kaz/Test ; /usr/bin/env /bin/python /home/kaz/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 38849 -- /home/kaz/Test/send.py 
Changing discoverable on succeeded
Changing discoverable on succeeded
trying to connect to E on PSM 0x4097
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.error: (112, 'Host is down')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaz/Test/send.py", line 20, in <module>
    TT_thread = toTwo(bt_addrs[0],send_data_list)
  File "/home/kaz/Test/sendandreceive.py", line 7, in toTwo
    target=l2cap_client(
  File "/home/kaz/Test/client.py", line 17, in l2cap_client
    sock.connect((bt_addr, port))
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: [Errno 112] Host is down

11/28
https://people.csail.mit.edu/albert/bluez-intro/x232.html
https://people.csail.mit.edu/albert/bluez-intro/x264.html
rfcommとl2capって何が違うの？　rfcommなら通信出来た。
